---

- name: Import the public key used by the package management system
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10
  # sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

- name: Create a list file for MongoDB
  template: src=mongodb-org-3.0.list dest=/etc/apt/sources.list.d/mongodb-org-3.0.list

- name: Install MongoDB 3.0.6
  apt: update_cache=yes state=present name={{ item }}
  with_items: 
     - "mongodb-org=3.0.6"
     - "mongodb-org-server=3.0.6"
     - "mongodb-org-shell=3.0.6"
     - "mongodb-org-mongos=3.0.6"
     - "mongodb-org-tools=3.0.6" 

- name: Pin a specific version of MongoDB
  shell: echo "{{ item }} hold" | sudo dpkg --set-selections
  with_items: 
    - "mongodb-org"
    - "mongodb-org-server"
    - "mongodb-org-shell"
    - "mongodb-org-mongos"
    - "mongodb-org-tools"

- name: Start MongoDB 
  service: state=restarted enabled=yes name=mongod

